import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Jersey City Bike Master Plan</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                [...Array(168).keys()].map(i => {
                    const id = (i + 1).toString()
                    return <a id={id} key={`slide-${id}`} href={`#${id}`}>
                        <Image
                            src={`/img/bmp-${id.padStart(3, '0')}.png`}
                            alt={`Slide ${id}`}
                            width={600}
                            height={450}
                            layout="responsive"
                            loading="lazy"
                        />
                    </a>
                })
            }
            <main className={styles.main}>
{/*
                <h1 className={styles.title}>
                    Jersey City Bike Master Plan
                </h1>
*/}
            </main>
        </div>
    )
}

export default Home
