name: Build + Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Build + Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: yarn-lock.json
      - run: npm install
      - name: Build
        run: |
          npm run build
          npm run export
          touch out/.nojekyll
      - name: Deploy to GH Page
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: ghp
          folder: out
